### PR TITLE
WIP: Simplified reporting for the wiki

### PR DESCRIPTION
**Pull request by jhall11**
Still cleaning up

### CODE REVIEW

**Comment by jhall11** [comment]
@kelvin-onlab, If you would like to keep the simplified plain text version, you can use this commit. I should be pushing the wiki version today.

Do you guys think it would be useful to have both a plain text and confluence/xhtml version?

**Comment by kelvin-onlab** [comment]
It wouldn't hurt to keep both. If we want to see the raw simplified logs
clearly ,right away, we can open the txt otherwise looking at the xhtml
version would be a pain. Maybe for now its good to keep both? :)

**Comment by jhall11** [comment]
ok, I think I can do that. I'm thinking there will be two files created, 
Summary.txt - What this commit has
Wiki.txt - same as above, plus the xhtml/confluence markup.

**Comment by kelvin-onlab** [comment]
sounds good!

**Comment by jhall11** [comment]
Can you let me know how this works for you kelvin?

**Comment by kelvin-onlab** [comment]
Okay Ill go ahead and try it, I'll let you know later.

**Comment by kelvin-onlab** [comment]
I noticed that the summary only prints the case" part not the steps".

**Comment by jhall11** [comment]
Do you use main.step statements? It seems to print them for me.

**Comment by kelvin-onlab** [comment]
Yes, I do main.step, maybe I'm doing something wrong? I only cherry picked
the .logger and teston files to my functionality.

**Comment by kelvin-onlab** [comment]
the wiki.txt prints correctly, just the summary.txt only prints case not
step

**Comment by jhall11** [comment]
You need the utilities file as well since I changed one of the variable names

**Comment by kelvin-onlab** [comment]
Okay, it looks good

**Comment by kelvin-onlab** [comment]
Added the changes in utilities files and it now works like before.

Thanks,

**Pull request merged**
