### PR TITLE
Modified multitosinglepoint intent driver function to accept any number ...

### PR DESCRIPTION
**Pull request by shahshreya**
...of ingress devices instead of just two

### CODE REVIEW

**Comment by shahshreya** [comment]
I know that the cli function implementation accepts a sequence of ingress devices

**Comment by shahshreya** [comment]
I think the system requires at least 2 sources

**Comment by shahshreya** [comment]
Added a checker to check if the length of the iterables in the zip function is equal

**Comment by shahshreya** [comment]
Yes.

**Comment by kelvin-onlab** [comment]
Thanks shreya! :)

**Pull request merged**
