### PR TITLE
Fix multiple cleanup bug caused by threading

### PR DESCRIPTION
**Pull request by jhall11**
Use a lock to guarantee that cleanup is called only once per test

### CODE REVIEW

**Comment by jhall11** [comment]
@hakrishn This should fix your issue with cleanup being called multiple times with exceptions in your CHO test

**Comment by kelvin-onlab** [comment]
Looks good! nice use of lock mechanism.

**Comment by kelvin-onlab** [comment]
Yup, no more errors

**Comment by kelvin-onlab** [comment]
Nvm, Is it this fix?

**Comment by kelvin-onlab** [comment]
I can't reproduce it now, i was just unlucky (lucky?) last time i guess.

**Pull request merged**
